version: "3.9"
services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=mongodb-admin
      - MONGODB_INITDB_ROOT_PASSWORD=mongodb-password-123
      # - MONGODB_INITDB_ROOT_USERNAME=UZKhBdzrfHkR9twe
      # - MONGODB_INITDB_ROOT_PASSWORD=wYyk3fMP!WnBqdRAha9XtxQVpEcuNHKv4-zGj*sr7S82CJe6FU
  # app:
  #   image: mealbase-lite:latest
  #   volumes:
  #     - /home/ec2-user/mealbase-lite/production/.env:/app/.env
  #   depends_on:
  #     - mongodb
  #   healthcheck:
  #     test: ["CMD-SHELL", "wget -qO- http://0.0.0.0:3000/api/echo || exit 1"]
  #     interval: 15s
  #     timeout: 3s
  #     retries: 1
  #     start_period: 15s
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #     update_config:
  #       monitor: 10s
  #       parallelism: 1
  #       order: start-first
  #       failure_action: rollback
  #     restart_policy:
  #       condition: on-failure
  #       delay: 5s
  #       max_attempts: 3
  #       window: 60s
